// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(CPRDbContext))]
    [Migration("20250523105058_Teste2")]
    partial class Teste2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrato")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Cliente.ClienteInfo", "ClienteInfo", b1 =>
                        {
                            b1.Property<int>("ClienteId")
                                .HasColumnType("int");

                            b1.Property<string>("Bairro")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Bairro");

                            b1.Property<string>("CEP")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CEP");

                            b1.Property<string>("Endereco")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Endereco");

                            b1.Property<string>("Telefone")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Telefone");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");

                            b1.OwnsOne("Domain.ValueObjects.Cliente.EmpresaInfo", "EmpresaInfo", b2 =>
                                {
                                    b2.Property<int>("ClienteInfoClienteId")
                                        .HasColumnType("int");

                                    b2.Property<string>("CNPJ")
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("CNPJ");

                                    b2.Property<string>("Fantasia")
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Fantasia");

                                    b2.Property<string>("InscricaoEstadual")
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("InscricaoEstadual");

                                    b2.Property<string>("RazaoSocial")
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("RazaoSocial");

                                    b2.HasKey("ClienteInfoClienteId");

                                    b2.ToTable("Clientes");

                                    b2.WithOwner()
                                        .HasForeignKey("ClienteInfoClienteId");
                                });

                            b1.OwnsOne("Domain.ValueObjects.Cliente.PessoaFisicaInfo", "PessoaFisicaInfo", b2 =>
                                {
                                    b2.Property<int>("ClienteInfoClienteId")
                                        .HasColumnType("int");

                                    b2.Property<string>("CPF")
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("CPF");

                                    b2.Property<string>("Nome")
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Nome");

                                    b2.HasKey("ClienteInfoClienteId");

                                    b2.ToTable("Clientes");

                                    b2.WithOwner()
                                        .HasForeignKey("ClienteInfoClienteId");
                                });

                            b1.Navigation("EmpresaInfo");

                            b1.Navigation("PessoaFisicaInfo");
                        });

                    b.Navigation("ClienteInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
